name: saverecipe
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^0.4.5
  cupertino_icons: ^0.1.3
  provider: ^4.1.2
  image_picker: ^0.6.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
